import { createContext, useContext, useEffect, useMemo, useState } from "react";
import * as SecureStore from "expo-secure-store";

const LanguageContext = createContext(null);

const translations = {
  en: {
    success: "Success",
    error: "Error",
    emailPasswordRequired: "Email and password are required",
    loginSuccess: "Logged in successfully",
    failedSaveSession: "Failed to save session",
    invalidCredentials: "Invalid credentials",
    loginFailed: "Login failed",
    enterEmail: "Enter email",
    enterPassword: "Enter password",
    signIn: "Sign In",
    forgotPassword: "Forgot Password?",
    noAccount: "Don't have an account? Sign Up",
    loginConsent: "By logging in, I consent to the Terms and Conditions & Privacy Policy",
    allFieldsRequired: "All fields are required",
    accountCreated: "Account created successfully",
    createAccount: "Create Account",
    name: "Name",
    email: "Email",
    phoneNumber: "Phone Number",
    address: "Address",
    password: "Password",
    signUp: "Sign Up",
    alreadyHaveAccount: "Already have an account? Sign In",
    emailRequired: "Email is required",
    resetLinkSent: "Reset Link Sent!",
    resetLinkInstructions: "Check your email for password reset instructions",
    resetEmailFailed: "Failed to send reset email",
    checkEmail: "Check Your Email",
    resetEmailSentPrefix: "We've sent a password reset link to",
    resetEmailExpiry: "Open the link in your email to create a new password. The link expires in 1 hour.",
    tryAnotherEmail: "Try Another Email",
    backToSignIn: "Back to Sign In",
    resetPassword: "Reset Password",
    resetPasswordDescription: "Enter your email to receive a password reset link",
    phoneNumber: "Phone number",
    phoneRequired: "A registered phone number is required",
    phoneNotRegistered: "This phone number is not registered",
    phoneVerified: "Phone number verified",
    phoneVerifiedDescription: "You can now create a new password.",
    verifyPhoneNumber: "Verify Phone Number",
    verifyPhoneDescription: "Enter the phone number registered to your account.",
    verifyPhone: "Verify Phone Number",
    verifying: "Verifying...",
    newPasswordForPhone: "Create a new password for",
    sending: "Sending...",
    sendResetLink: "Send Reset Link",
    invalidLink: "Invalid Link",
    invalidLinkDescription: "The password reset link is invalid or has expired.",
    requestNewLink: "Request New Link",
    createNewPassword: "Create New Password",
    newPassword: "New password",
    retypePassword: "Re-type password",
    resetting: "Resetting...",
    logout: "Logout",
    logoutQuestion: "Are you sure you want to log out?",
    cancel: "Cancel",
    acceptPickup: "Accept Pickup",
    rejectPickup: "Reject Pickup",
    rejectionReason: "Reason for rejection",
    rejectionReasonPlaceholder: "Explain why this pickup request is being rejected",
    rejectionReasonRequired: "Please enter a reason for rejection",
    rejectionSubmitted: "The rejection reason has been sent to the vendor",
    acceptPickupQuestion: "Are you sure you want to accept this pickup request?",
    rejectPickupQuestion: "Are you sure you want to reject this pickup request?",
    pickupUpdated: "Pickup request updated successfully",
    pickupUpdateFailed: "Failed to update pickup request",
    welcomeBack: "Welcome back,",
    dailyPrices: "Daily Prices",
    pickupRequests: "Pickup Requests",
    noPickupRequests: "No pickup requests found",
    order: "Order",
    category: "Category",
    quantity: "Quantity",
    items: "items",
    price: "Price",
    phone: "Phone",
    dropPoint: "Drop Point",
    created: "Created",
    note: "Note",
    accept: "Accept",
    reject: "Reject",
    viewDetails: "View Details",
    pending: "Pending",
    assigned: "Assigned",
    completed: "Completed",
    cancelled: "Cancelled",
  },
  sw: {
    success: "Mafanikio",
    error: "Hitilafu",
    emailPasswordRequired: "Barua pepe na nenosiri vinahitajika",
    loginSuccess: "Umeingia kwa mafanikio",
    failedSaveSession: "Imeshindikana kuhifadhi kipindi cha kuingia",
    invalidCredentials: "Taarifa za kuingia si sahihi",
    loginFailed: "Kuingia kumeshindikana",
    enterEmail: "Weka barua pepe",
    enterPassword: "Weka nenosiri",
    signIn: "Ingia",
    forgotPassword: "Umesahau nenosiri?",
    noAccount: "Huna akaunti? Jisajili",
    loginConsent: "Kwa kuingia, nakubali Sheria na Masharti pamoja na Sera ya Faragha",
    allFieldsRequired: "Sehemu zote zinahitajika",
    accountCreated: "Akaunti imetengenezwa kwa mafanikio",
    createAccount: "Tengeneza Akaunti",
    name: "Jina",
    email: "Barua pepe",
    phoneNumber: "Namba ya simu",
    address: "Anwani",
    password: "Nenosiri",
    signUp: "Jisajili",
    alreadyHaveAccount: "Tayari una akaunti? Ingia",
    emailRequired: "Barua pepe inahitajika",
    resetLinkSent: "Kiungo cha Kurejesha Nenosiri Kimetumwa!",
    resetLinkInstructions: "Angalia barua pepe yako kwa maelekezo ya kurejesha nenosiri",
    resetEmailFailed: "Imeshindikana kutuma barua pepe ya kurejesha nenosiri",
    checkEmail: "Angalia Barua Pepe Yako",
    resetEmailSentPrefix: "Tumetuma kiungo cha kurejesha nenosiri kwa",
    resetEmailExpiry: "Fungua kiungo kwenye barua pepe yako kutengeneza nenosiri jipya. Kiungo kinaisha baada ya saa 1.",
    tryAnotherEmail: "Jaribu Barua Pepe Nyingine",
    backToSignIn: "Rudi Kuingia",
    resetPassword: "Rejesha Nenosiri",
    resetPasswordDescription: "Weka barua pepe yako upokee kiungo cha kurejesha nenosiri",
    phoneNumber: "Namba ya simu",
    phoneRequired: "Namba ya simu iliyosajiliwa inahitajika",
    phoneNotRegistered: "Namba hii ya simu haijasajiliwa",
    phoneVerified: "Namba ya simu imethibitishwa",
    phoneVerifiedDescription: "Sasa unaweza kutengeneza nenosiri jipya.",
    verifyPhoneNumber: "Thibitisha Namba ya Simu",
    verifyPhoneDescription: "Weka namba ya simu iliyosajiliwa kwenye akaunti yako.",
    verifyPhone: "Thibitisha Namba ya Simu",
    verifying: "Inathibitisha...",
    newPasswordForPhone: "Tengeneza nenosiri jipya kwa",
    sending: "Inatuma...",
    sendResetLink: "Tuma Kiungo cha Kurejesha",
    invalidLink: "Kiungo Si Sahihi",
    invalidLinkDescription: "Kiungo cha kurejesha nenosiri si sahihi au muda wake umeisha.",
    requestNewLink: "Omba Kiungo Kipya",
    createNewPassword: "Tengeneza Nenosiri Jipya",
    newPassword: "Nenosiri jipya",
    retypePassword: "Andika nenosiri tena",
    resetting: "Inarejesha...",
    logout: "Toka",
    logoutQuestion: "Una uhakika unataka kutoka?",
    cancel: "Ghairi",
    acceptPickup: "Kubali Ombi",
    rejectPickup: "Kataa Ombi",
    rejectionReason: "Sababu ya kukataa",
    rejectionReasonPlaceholder: "Eleza kwa nini ombi hili la kuchukua taka linakataliwa",
    rejectionReasonRequired: "Tafadhali weka sababu ya kukataa",
    rejectionSubmitted: "Sababu ya kukataa imetumwa kwa muuzaji",
    acceptPickupQuestion: "Una uhakika unataka kukubali ombi hili la kuchukua taka?",
    rejectPickupQuestion: "Una uhakika unataka kukataa ombi hili la kuchukua taka?",
    pickupUpdated: "Ombi la kuchukua taka limesasishwa kwa mafanikio",
    pickupUpdateFailed: "Imeshindikana kusasisha ombi la kuchukua taka",
    welcomeBack: "Karibu tena,",
    dailyPrices: "Bei za Leo",
    pickupRequests: "Maombi ya Kuchukua Taka",
    noPickupRequests: "Hakuna maombi ya kuchukua taka",
    order: "Oda",
    category: "Aina",
    quantity: "Kiasi",
    items: "vitu",
    price: "Bei",
    phone: "Simu",
    dropPoint: "Eneo la kupeleka",
    created: "Imeundwa",
    note: "Maelezo",
    accept: "Kubali",
    reject: "Kataa",
    viewDetails: "Tazama Maelezo",
    pending: "Inasubiri",
    assigned: "Imepangiwa",
    completed: "Imekamilika",
    cancelled: "Imeghairiwa",
  },
};

export function LanguageProvider({ children }) {
  const [language, setCurrentLanguage] = useState("en");

  useEffect(() => {
    SecureStore.getItemAsync("language").then((savedLanguage) => {
      if (savedLanguage === "en" || savedLanguage === "sw") setCurrentLanguage(savedLanguage);
    }).catch(() => {});
  }, []);

  const value = useMemo(() => ({
    language,
    setLanguage: async (nextLanguage) => {
      if (nextLanguage !== "en" && nextLanguage !== "sw") return;
      setCurrentLanguage(nextLanguage);
      try {
        await SecureStore.setItemAsync("language", nextLanguage);
      } catch {
        // The chosen language remains active for this session if storage is unavailable.
      }
    },
    t: (key) => translations[language]?.[key] ?? translations.en[key] ?? key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
